picknplace_node:
  ros__parameters:
    # --- Gripper Settings ---
    gripper_open: 130
    gripper_close: 142
    
    # --- Poses [j1, j2, j3, j4, j5, j6, time_ms] ---
    
    # 8) Initial Pose; Home
    pose_home: [90, 90, 50, -40, 90, 90, 3000]

    # Supply Sequence Poses
    supply_sequence:
      supply_hover_1: [0, 60, 30, 0, 90, 120, 2500]
      pre_grasp_1: [0, 30, 45, 13, 90, 120, 2500]
      down:        [0, 12, 43, 31, 90, 120, 2500] # Note: Gripper is closed here
      pre_grasp_2: [0, 30, 45, 13, 90, 142, 2500]
      supply_hover_2: [0, 60, 30, 0, 90, 142, 2500] 
      board_hover: [90, 60, 30, 0, 90, 142, 2500]

    # 10l) Target Cells (1-9)
    targets:
      cell_1:
        pre_grasp_1: [110, 49, 18, 28, 72, 142, 2500]
        down:        [108, 28, 17, 44, 72, 142, 2500]
        open:        [108, 28, 17, 44, 72, 130, 2000]
        pre_grasp_2: [110, 49, 18, 28, 72, 130, 2500]
      cell_2:
        pre_grasp_1: [90, 53, 9, 32, 90, 142, 2500]
        down:        [90, 36, 2, 52, 90, 142, 2500]
        open:        [90, 36, 2, 52, 90, 130, 2000]
        pre_grasp_2: [90, 53, 9, 32, 90, 130, 2500]
      cell_3:
        pre_grasp_1: [68, 45, 17, 33, 108, 142, 2500]
        down:        [69, 26, 18, 45, 108, 142, 2500]
        open:        [69, 26, 18, 45, 108, 130, 2000]
        pre_grasp_2: [68, 45, 17, 33, 108, 130, 2500]
      cell_4:
        pre_grasp_1: [106, 15, 75, 5, 76, 142, 2500]
        down:        [105, 1, 71, 19, 76, 142, 2500]
        open:        [105, 1, 71, 19, 76, 130, 2000]
        pre_grasp_2: [106, 15, 75, 5, 76, 130, 2500]
      cell_5:
        pre_grasp_1: [90, 40, 35, 25, 90, 142, 2500]
        down:        [90, 12, 47, 36, 90, 142, 2500]
        open:        [90, 12, 47, 36, 90, 130, 2000]
        pre_grasp_2: [90, 40, 35, 25, 90, 130, 2500]
      cell_6:
        pre_grasp_1: [74, 19, 76, 0, 105, 142, 2500]
        down:        [75, 0, 78, 14, 105, 142, 2500]
        open:        [75, 0, 78, 14, 105, 130, 2000]
        pre_grasp_2: [74, 19, 76, 0, 105, 130, 2500]
      cell_7:
        pre_grasp_1: [104, 28, 56, 24, 79, 142, 2500]
        down:        [102, 0, 72, 35, 79, 142, 2500]
        open:        [102, 0, 72, 35, 79, 130, 2000]
        pre_grasp_2: [104, 28, 56, 24, 79, 130, 2500]
      cell_8:
        pre_grasp_1: [90, 28, 56, 24, 90, 142, 2500]
        down:        [90, 9, 54, 41, 90, 142, 2500]
        open:        [90, 9, 54, 41, 90, 130, 2000]
        pre_grasp_2: [90, 28, 56, 24, 90, 130, 2500]
      cell_9:
        pre_grasp_1: [77, 44, 19, 60, 99, 142, 2500]
        down:        [79, 0, 73, 33, 105, 142, 2500]
        open:        [79, 0, 73, 33, 105, 130, 2000]
        pre_grasp_2: [77, 44, 19, 60, 99, 130, 2500]
